# Generated by Django 6.1.1 on 2026-09-08 18:00

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('kind', models.CharField(choices=[('single', 'One correct answer'), ('multi', 'Several correct answers'), ('short', 'Short written answer')], default='single', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('general', 'General'), ('chapter', 'School-specific')], default='general', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pass_threshold', models.PositiveIntegerField(default=70, help_text='Percentage of questions that must be correct to pass.')),
                ('allow_retake', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, help_text='Required when the scope is school-specific.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chapter')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('school_identifier', models.CharField(max_length=60)),
                ('score', models.PositiveIntegerField(default=0, help_text='Number of questions answered correctly.')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('attendance_code_given', models.CharField(blank=True, max_length=40)),
                ('credit_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('exported', 'Exported to SONA'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('credit_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.chapter')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='events.event')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.submission')),
            ],
            options={
                'ordering': ['question__position'],
            },
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(models.F('quiz'), django.db.models.functions.text.Lower('school_identifier'), name='one_submission_per_student_per_quiz'),
        ),
    ]
