# Generated by Django 6.1.1 on 2026-09-08 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('university', 'University'), ('high_school', 'High school')], default='university', max_length=20)),
                ('collects_submissions', models.BooleanField(default=True, help_text='Whether students at this chapter may submit quizzes. Always off for high schools.')),
                ('sona_enabled', models.BooleanField(default=False, help_text="Turn on once the department's participant pool coordinator has approved credit.")),
                ('identifier_label', models.CharField(default='Student ID', help_text="What this school calls the ID students enter, e.g. 'GT ID' or 'NetID'.", max_length=60)),
                ('identifier_pattern', models.CharField(blank=True, help_text='Optional regex the identifier must match, e.g. ^90\\d{7}$. Leave blank to accept anything.', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('chapter_admin', 'Chapter admin'), ('owner', 'Owner')], default='officer', max_length=20)),
                ('chapter', models.ForeignKey(blank=True, help_text='Leave blank for org-wide access across every chapter.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chapter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('link', 'External link'), ('file', 'Uploaded file')], default='link', max_length=10)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='resources/')),
                ('published', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(blank=True, help_text="Leave blank to show on every chapter's page.", null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chapter')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
    ]
