# Generated by Django 6.1.1 on 2026-09-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One line shown in listings.', max_length=280)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('credit_value', models.DecimalField(decimal_places=2, default=0, help_text="SONA credits granted for attending. 0 if this event isn't credit-bearing.", max_digits=4)),
                ('attendance_code', models.CharField(blank=True, help_text='Read this out in the last few minutes. Students type it into the quiz. Leave blank to skip attendance verification.', max_length=40)),
                ('published', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(blank=True, help_text='Leave blank for an org-wide event open to every chapter.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.chapter')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
